(() => {
  'use strict';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const state={view:'home',games:[],query:'',category:'All',installed:new Set(JSON.parse(localStorage.getItem('arc.installed')||'[]')),favorites:new Set(JSON.parse(localStorage.getItem('arc.favorites')||'[]')),searchIndex:0,motion:localStorage.getItem('arc.motion')!=='0'};
  const save=()=>{localStorage.setItem('arc.installed',JSON.stringify([...state.installed]));localStorage.setItem('arc.favorites',JSON.stringify([...state.favorites]))};
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const icon=n=>`<i data-lucide="${n}"></i>`;
  const toast=(title,text='')=>{const el=document.createElement('div');el.className='toast';el.innerHTML=`${icon('check-circle-2')}<div><strong>${esc(title)}</strong><p>${esc(text)}</p></div>`;$('#toastStack').appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),350)},3200);window.lucide?.createIcons({attrs:{'stroke-width':1.5}})};
  function applySettings(){const root=document.documentElement;const theme=localStorage.getItem('arc.theme')||'dark';root.dataset.theme=theme==='system'?(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'):theme;root.style.setProperty('--accent',localStorage.getItem('arc.accent')||'#8b5cf6');root.style.setProperty('--opacity',(localStorage.getItem('arc.opacity')||66)/100);root.style.setProperty('--glass',`rgba(22,24,31,${(localStorage.getItem('arc.opacity')||66)/100})`);root.style.setProperty('--blur',(localStorage.getItem('arc.blur')||20)+'px');root.classList.toggle('reduce-motion',!state.motion)}
  function reveal(){const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.08});$$('.reveal,.game-card').forEach((e,i)=>{e.style.transitionDelay=`${Math.min(i*35,280)}ms`;obs.observe(e)})}
  const cover=g=>g.cover?`<img loading="lazy" src="${esc(g.cover)}" alt="${esc(g.name)} cover">`:`<div class="cover-fallback">ARC+</div>`;
  function card(g){const fav=state.favorites.has(g.id);return `<article class="game-card reveal"><div class="cover">${cover(g)}<span class="badge">${esc(g.zone)}</span><div class="card-overlay"><button class="overlay-btn primary" data-play="${esc(g.id)}" aria-label="Play ${esc(g.name)}">${icon('play')}</button><button class="overlay-btn" data-fav="${esc(g.id)}" aria-label="${fav?'Remove from':'Add to'} favorites">${icon(fav?'heart-off':'heart')}</button><button class="overlay-btn" data-share="${esc(g.id)}" aria-label="Share ${esc(g.name)}">${icon('share-2')}</button></div></div><div class="card-body"><div class="card-title"><h3>${esc(g.name)}</h3><span class="rating">${icon('star')} ${g.rating?esc(g.rating):'—'}</span></div><div class="meta"><span class="tag">${esc(g.category)}</span>${(g.tags||[]).slice(0,2).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><p class="card-desc">${esc(g.description||'Ready to play.')}</p></div></article>`}
  function bindCards(){ $$('[data-play]').forEach(b=>b.onclick=()=>{const g=state.games.find(x=>x.id===b.dataset.play);if(g)launch(g)});$$('[data-fav]').forEach(b=>b.onclick=()=>{state.favorites.has(b.dataset.fav)?state.favorites.delete(b.dataset.fav):state.favorites.add(b.dataset.fav);save();render()});$$('[data-share]').forEach(b=>b.onclick=async()=>{const g=state.games.find(x=>x.id===b.dataset.share);if(!g)return;const url=new URL(g.url,location.href).href;try{await navigator.clipboard.writeText(url);toast('Link copied',g.name)}catch{toast('Share link',url)}})}
  function launch(g){$('#playerOverlay').hidden=false;$('#gameFrame').src=g.url;document.body.style.overflow='hidden';toast('Launching',g.name)}
  function closePlayer(){$('#playerOverlay').hidden=true;$('#gameFrame').src='about:blank';document.body.style.overflow=''}
  function filtered(){const q=state.query.trim().toLowerCase();return state.games.filter(g=>(state.category==='All'||g.category===state.category)&&(!q||`${g.name} ${g.category} ${g.description} ${(g.tags||[]).join(' ')}`.toLowerCase().includes(q)))}
  function shell(title,eyebrow,desc,content,actions=''){return `<div class="page-head"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${desc}</p></div>${actions}</div>${content}`}
  function renderHome(){const featured=state.games[0];const recent=state.games.filter(g=>state.installed.has(g.id)).slice(0,4);$('#homeView').innerHTML=featured?`<section class="hero glass"><div><span class="eyebrow">FEATURED · ${esc(featured.category)}</span><h1>Play something<br><em>worth your time.</em></h1><p>Arc+ brings your game collection into one fast, glassy interface. No build step, no account required, and your library stays on this device.</p><div class="hero-actions"><button class="btn primary" data-play="${esc(featured.id)}">${icon('play')} Play now</button><button class="btn" data-route="store">${icon('compass')} Explore library</button></div></div><div class="hero-art"><img src="${esc(featured.cover||'./offline/logo.png')}" alt=""><span class="live-pill"><i></i> ${state.games.length} games available</span></div></section><section class="section"><div class="section-head"><div><span class="eyebrow">YOUR COLLECTION</span><h2>${recent.length?'Jump back in':'Start playing'}</h2><p>${recent.length?'Recently installed games.':'Your library is ready when you are.'}</p></div><button class="link-btn" data-route="library">View library ${icon('arrow-up-right')}</button></div><div class="game-grid">${recent.length?recent.map(card).join(''):`<div class="empty glass">${icon('library')}<h3>Your library is empty</h3><p>Pick a game from the Store and it will live here.</p><button class="btn primary" data-route="store">${icon('store')} Browse games</button></div>`}</div></section>`:`<div class="empty glass">${icon('loader-circle')}<h3>Loading games</h3><p>Reading the current catalogue.</p></div>`;bindCards()}
  function renderStore(){const cats=['All',...new Set(state.games.map(g=>g.category))];const games=filtered();$('#storeView').innerHTML=shell('Store','DISCOVER',`${state.games.length} games in the current catalogue.`,`${'<div class="filter-row">'+cats.map(c=>`<button class="filter ${state.category===c?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('')+'</div>'}<div class="search-bar">${icon('search')}<input id="storeSearch" value="${esc(state.query)}" placeholder="Search games…"></div><div class="game-grid" style="margin-top:18px">${games.map(card).join('')||`<div class="empty glass">${icon('search-x')}<h3>No matches</h3><p>Try a different title, genre or tag.</p></div>`}</div>`);$('#storeSearch').oninput=e=>{state.query=e.target.value;renderStore()};$$('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderStore()});bindCards()}
  function renderLibrary(){const games=state.games.filter(g=>state.installed.has(g.id));$('#libraryView').innerHTML=shell('Library','YOUR COLLECTION',`${games.length} installed game${games.length===1?'':'s'} saved locally.`, `<div class="library-hero glass"><div class="stat"><span class="stat-icon">${icon('library')}</span><div><strong>${games.length}</strong><span>installed</span></div></div><button class="btn" data-route="store">${icon('plus')} Add games</button></div><div class="game-grid">${games.map(card).join('')||`<div class="empty glass">${icon('library')}<h3>Nothing here yet</h3><p>Install a game from the Store to build your collection.</p><button class="btn primary" data-route="store">${icon('store')} Open Store</button></div>`}</div>`);bindCards()}
  function renderSocial(){$('#socialView').innerHTML=shell('Social','SOCIAL','A quiet place for the next Arc+ social layer.',`<div class="social-card glass reveal"><div>${icon('users')}<h2>Friends are coming.</h2><p>The current v2 catalogue is local and static-first, so there is no fake online activity or fabricated player data here. When a real social backend exists, this surface is ready for it.</p></div></div>`)}
  function renderProfile(){$('#profileView').innerHTML=shell('Profile','LOCAL PROFILE','Your Arc+ preferences live on this device.',`<div class="social-card glass"><div><span class="avatar large"><span></span><img src="./offline/logo.png" alt=""></span><h2>Player</h2><p>${state.installed.size} installed · ${state.favorites.size} favorites</p><button class="btn primary" id="profileSettings">${icon('settings')} Open settings</button></div></div>`);$('#profileSettings').onclick=openSettings}
  function render(){renderHome();renderStore();renderLibrary();renderSocial();renderProfile();setRouteUI();reveal();window.lucide?.createIcons({attrs:{'stroke-width':1.5}})}
  function setRouteUI(){const items=$$('[data-route]');items.forEach(b=>b.classList.toggle('active',b.dataset.route===state.view));const active=$('.desktop-nav .nav-item.active'),indicator=$('.nav-indicator');if(active&&indicator){indicator.style.width=`${active.offsetWidth}px`;indicator.style.transform=`translateX(${active.offsetLeft}px)`}}
  function route(view){if(!['home','library','store','social','profile'].includes(view))view='home';state.view=view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));setRouteUI();window.scrollTo({top:0,behavior:state.motion?'smooth':'auto'});render();$('#app').focus({preventScroll:true})}
  function openSearch(){const back=$('#searchBackdrop');back.hidden=false;const input=$('#searchInput');input.value=state.query;input.focus();updateSearch();window.lucide?.createIcons({attrs:{'stroke-width':1.5}})}
  function closeModal(id){$('#'+id).hidden=true}
  function updateSearch(){const q=$('#searchInput').value.trim().toLowerCase();const results=state.games.filter(g=>!q||`${g.name} ${g.category} ${g.description} ${(g.tags||[]).join(' ')}`.toLowerCase().includes(q)).slice(0,12);state.searchIndex=Math.min(state.searchIndex,Math.max(0,results.length-1));$('#searchResults').innerHTML=results.length?results.map((g,i)=>`<div class="search-result ${i===state.searchIndex?'selected':''}" data-search-play="${esc(g.id)}"><span class="result-cover">${cover(g)}</span><span class="result-copy"><strong>${esc(g.name)}</strong><span>${esc(g.category)} · ${esc(g.zone)}</span></span>${icon('arrow-up-right')}</div>`).join(''):`<div class="empty">${icon('search-x')}<h3>No games found</h3><p>Try another search.</p></div>`;$$('[data-search-play]').forEach(b=>b.onclick=()=>{const g=state.games.find(x=>x.id===b.dataset.searchPlay);closeModal('searchBackdrop');if(g)launch(g)});window.lucide?.createIcons({attrs:{'stroke-width':1.5}})}
  function openSettings(){closeModal('profilePanel');$('#settingsPanel').hidden=false;syncSettings();window.lucide?.createIcons({attrs:{'stroke-width':1.5}})}
  function syncSettings(){const theme=localStorage.getItem('arc.theme')||'dark';$$('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===theme));$('#accentPicker').value=localStorage.getItem('arc.accent')||'#8b5cf6';$('#opacityRange').value=localStorage.getItem('arc.opacity')||66;$('#opacityValue').value=`${$('#opacityRange').value}%`;$('#blurRange').value=localStorage.getItem('arc.blur')||20;$('#blurValue').value=`${$('#blurRange').value}px`;$('.switch').classList.toggle('on',state.motion)}
  function notifications(){const list=$('#notificationList');list.innerHTML=`<div class="notification">${icon('sparkles')}<div><strong>Arc+ is ready</strong><p>The new liquid-glass interface is running from the v2 branch.</p></div></div><div class="notification">${icon('database')}<div><strong>Catalogue loaded</strong><p>${state.games.length} real entries were read from the repository catalogue.</p></div></div>`;$('#notificationsBackdrop').hidden=false;$('#notificationBadge').style.display='none';window.lucide?.createIcons({attrs:{'stroke-width':1.5}})}
  function init(){applySettings();$$('[data-route]').forEach(b=>b.onclick=e=>{e.preventDefault();route(b.dataset.route)});$('#openSearch').onclick=openSearch;$('#openNotifications').onclick=notifications;$('#openProfile').onclick=()=>{$('#profilePanel').hidden=false;$('#profileGames').textContent=state.installed.size;$('#profileTotal').textContent=state.games.length;window.lucide?.createIcons({attrs:{'stroke-width':1.5}})};$('#openSettings').onclick=openSettings;$('#closePlayer').onclick=closePlayer;$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$('#searchInput').oninput=e=>{state.query=e.target.value;state.searchIndex=0;updateSearch()};$('#searchBackdrop').onclick=e=>{if(e.target===e.currentTarget)closeModal('searchBackdrop')};$('#notificationsBackdrop').onclick=e=>{if(e.target===e.currentTarget)closeModal('notificationsBackdrop')};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape'){$('#searchBackdrop').hidden=true;$('#notificationsBackdrop').hidden=true;$('#settingsPanel').hidden=true;$('#profilePanel').hidden=true;if(!$('#playerOverlay').hidden)closePlayer()}if(!$('#searchBackdrop').hidden&&['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const n=$$('#searchResults .search-result').length;state.searchIndex=n?Math.max(0,Math.min(n-1,state.searchIndex+(e.key==='ArrowDown'?1:-1))):0;updateSearch()}if(!$('#searchBackdrop').hidden&&e.key==='Enter'){const b=$$('#searchResults .search-result')[state.searchIndex];b?.click()}});$('#themeChoices').onclick=e=>{const b=e.target.closest('[data-theme]');if(!b)return;localStorage.setItem('arc.theme',b.dataset.theme);applySettings();syncSettings()};$('#accentPicker').oninput=e=>{localStorage.setItem('arc.accent',e.target.value);applySettings()};$('#opacityRange').oninput=e=>{localStorage.setItem('arc.opacity',e.target.value);applySettings();$('#opacityValue').value=`${e.target.value}%`};$('#blurRange').oninput=e=>{localStorage.setItem('arc.blur',e.target.value);applySettings();$('#blurValue').value=`${e.target.value}px`};$('#toggleMotion').onclick=()=>{state.motion=!state.motion;localStorage.setItem('arc.motion',state.motion?'1':'0');applySettings();syncSettings()};$('#clearLibrary').onclick=()=>{state.installed.clear();save();toast('Library cleared','Your locally saved games were removed.');render()};$('#profileSettings').onclick=openSettings;window.addEventListener('storage',applySettings);ArcData.load().then(g=>{state.games=g;render();$('#notificationBadge').style.display='block'}).catch(()=>{state.games=[];render()});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
