(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const icon=n=>`<i data-lucide="${n}"></i>`;
const esc=v=>FlashData.esc(v);
const cfg={apiKey:'AIzaSyBprG8pYZ1WQNh2wt0kih3P7Z3nIxhnU5k',authDomain:'mobify-5b3c9.firebaseapp.com',projectId:'mobify-5b3c9',storageBucket:'mobify-5b3c9.firebasestorage.app',messagingSenderId:'454093361079',appId:'1:454093361079:web:ab1e1093a91a705be3a232'};
const ROLES=new Set(['admin','administrator','mod','moderator','owner']);
const state={view:location.hash.slice(1)||'home',games:[],installed:new Set(JSON.parse(localStorage.getItem('flashgames.installed')||'[]')),favorites:new Set(JSON.parse(localStorage.getItem('flashgames.favorites')||'[]')),query:'',category:'All',searchIndex:0,motion:localStorage.getItem('flashgames.motion')!=='0',user:null,profile:null,role:'',db:null,auth:null,notifications:[],presence:null,legacyHistory:[]};
const icons=()=>window.lucide?.createIcons({attrs:{'stroke-width':1.5}});
function save(){localStorage.setItem('flashgames.installed',JSON.stringify([...state.installed]));localStorage.setItem('flashgames.favorites',JSON.stringify([...state.favorites]));}
function prefs(){let theme=localStorage.getItem('flashgames.theme')||'dark';if(theme==='system')theme=matchMedia('(prefers-color-scheme:light)').matches?'light':'dark';const r=document.documentElement;r.dataset.theme=theme;r.style.setProperty('--accent',localStorage.getItem('flashgames.accent')||'#8b5cf6');r.style.setProperty('--opacity',(localStorage.getItem('flashgames.opacity')||66)/100);r.style.setProperty('--blur',(localStorage.getItem('flashgames.blur')||20)+'px');r.classList.toggle('reduce-motion',!state.motion)}
function toast(title,text=''){const t=document.createElement('div');t.className='toast';t.innerHTML=`${icon('info')}<div><strong>${esc(title)}</strong><p>${esc(text)}</p></div>`;$('#toastStack').append(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),350)},3600);icons();}
function empty(title,text,action=''){return `<div class="empty glass">${icon('inbox')}<h3>${esc(title)}</h3><p>${esc(text)}</p>${action}</div>`}
function cover(g){return g.cover?`<img loading="lazy" src="${esc(g.cover)}" alt="${esc(g.name)} cover" onerror="this.closest('.cover').classList.add('cover-missing');this.remove()">`:`<div class="cover-fallback">${esc(g.name.slice(0,2).toUpperCase())}</div>`}
function card(g){const installed=state.installed.has(g.id),fav=state.favorites.has(g.id);return `<article class="game-card reveal"><div class="cover">${cover(g)}<span class="badge">${esc(g.zone)}</span><div class="card-overlay"><button class="overlay-btn primary" data-play="${esc(g.id)}" aria-label="Play ${esc(g.name)}">${icon('play')}</button><button class="overlay-btn" data-fav="${esc(g.id)}" aria-label="${fav?'Remove from favorites':'Favorite'}">${icon(fav?'heart-off':'heart')}</button><button class="overlay-btn" data-share="${esc(g.id)}" aria-label="Share ${esc(g.name)}">${icon('share-2')}</button></div></div><div class="card-body"><div class="card-title"><h3>${esc(g.name)}</h3>${g.rating?`<span class="rating">${icon('star')} ${esc(g.rating)}</span>`:''}</div><div class="meta"><span class="tag">${esc(g.category)}</span>${(g.tags||[]).slice(0,2).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><p class="card-desc">${esc(g.description||'')}</p><button class="btn ${installed?'primary':''} full" data-${installed?'play':'install'}="${esc(installed?g.id:g.id)}">${icon(installed?'play':'download')} ${installed?'Play':'Add to library'}</button></div></article>`}
function bindCards(){
 $$('[data-play]').forEach(b=>b.onclick=()=>{const g=state.games.find(x=>x.id===b.dataset.play);if(g)launch(g)});
 $$('[data-install]').forEach(b=>b.onclick=()=>{state.installed.add(b.dataset.install);save();toast('Added to library','Saved locally on this device.');renderAll()});
 $$('[data-fav]').forEach(b=>b.onclick=()=>{state.favorites.has(b.dataset.fav)?state.favorites.delete(b.dataset.fav):state.favorites.add(b.dataset.fav);save();renderAll()});
 $$('[data-share]').forEach(b=>b.onclick=async()=>{const g=state.games.find(x=>x.id===b.dataset.share);if(!g)return;const url=new URL(g.url,location.href).href;try{await navigator.clipboard.writeText(url);toast('Link copied',g.name)}catch{toast('Share link',url)}});
 icons();reveal();
}
function reveal(){if(!('IntersectionObserver' in window)){ $$('.reveal').forEach(e=>e.classList.add('visible')); return;}const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach((e,i)=>{e.style.transitionDelay=`${Math.min(i*30,240)}ms`;observer.observe(e)});}
function setRoute(v){if(!['home','library','store','social','updates','admin'].includes(v))v='home';state.view=v;location.hash=v;$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('[data-route]').forEach(x=>x.classList.toggle('active',x.dataset.route===v));const active=$('.desktop-nav .nav-item.active'),ind=$('.nav-indicator');if(active&&ind){ind.style.width=active.offsetWidth+'px';ind.style.transform=`translateX(${active.offsetLeft}px)`}window.scrollTo({top:0,behavior:state.motion?'smooth':'auto'});renderCurrent();}
function renderCurrent(){renderHome();renderLibrary();renderStore();renderSocial();renderUpdates();if(state.role&&ROLES.has(state.role))renderAdmin();$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view));icons();}
function renderHome(){const el=$('#homeView');if(!el)return;const featured=state.games[0],recent=state.games.filter(g=>state.installed.has(g.id)).slice(0,4);if(!featured){el.innerHTML=empty('No catalogue loaded','The real legacy catalogue could not be reached. Refresh to retry.',`<button class="btn primary" id="retryCatalogue">${icon('refresh')} Retry</button>`);$('#retryCatalogue')?.addEventListener('click',()=>loadData(true));return;}el.innerHTML=`<section class="hero glass"><div><span class="eyebrow">FLASH GAMES · FEATURED</span><h1>Play something<br><em>worth your time.</em></h1><p>The current Flash Games catalogue, restored from the real legacy store and offline collection. No invented titles.</p><div class="hero-actions"><button class="btn primary" data-play="${esc(featured.id)}">${icon('play')} Play now</button><button class="btn" data-route="store">${icon('compass')} Explore store</button></div></div><div class="hero-art"><img src="${esc(featured.cover||'./offline/logo.png')}" alt="${esc(featured.name)}"><span class="live-pill"><i></i><span id="liveCount">Checking live players…</span></span></div></section><section class="section"><div class="section-head"><div><span class="eyebrow">YOUR COLLECTION</span><h2>${recent.length?'Jump back in':'Start playing'}</h2><p>${recent.length?'Recently saved games.':'Install a game from the Store to build your library.'}</p></div><button class="link-btn" data-route="library">View library ${icon('arrow-right')}</button></div><div class="game-grid">${recent.length?recent.map(card).join(''):empty('Your library is empty','Pick a real game from the Store.',`<button class="btn primary" data-route="store">${icon('store')} Browse games</button>`)}</div></section><section class="section"><div class="section-head"><div><span class="eyebrow">CATALOGUE</span><h2>${state.games.length.toLocaleString()} games</h2><p>Loaded from the repository data layer.</p></div><button class="link-btn" data-route="store">Open store ${icon('arrow-right')}</button></div></section>`;bindRoutes();bindCards();FlashData.getPresenceCount().then(n=>{state.presence=n;const x=$('#liveCount');if(x)x.textContent=n==null?'Live count unavailable':`${n.toLocaleString()} online`});}
function filtered(){const q=state.query.toLowerCase().trim();return state.games.filter(g=>(state.category==='All'||g.category===state.category)&&(!q||`${g.name} ${g.category} ${g.description} ${(g.tags||[]).join(' ')}`.toLowerCase().includes(q)))}
function renderStore(){const el=$('#storeView');if(!el)return;const cats=['All',...new Set(state.games.map(g=>g.category).filter(Boolean))],games=filtered();el.innerHTML=`<div class="page-head"><div><span class="eyebrow">DISCOVER</span><h1>Store</h1><p>${state.games.length.toLocaleString()} real games available from the restored catalogue.</p></div><label class="search-bar">${icon('search')}<input id="storeSearch" value="${esc(state.query)}" placeholder="Search games…"></label></div><div class="filter-row">${cats.map(c=>`<button class="filter ${state.category===c?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('')}</div><div class="game-grid">${games.map(card).join('')||empty('No matches','Try another title, genre or tag.')}</div>`;$('#storeSearch').oninput=e=>{state.query=e.target.value;renderStore()};$$('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderStore()});bindCards();}
function renderLibrary(){const el=$('#libraryView');if(!el)return;const games=state.games.filter(g=>state.installed.has(g.id));el.innerHTML=`<div class="page-head"><div><span class="eyebrow">YOUR COLLECTION</span><h1>Library</h1><p>${games.length} saved game${games.length===1?'':'s'} on this device.</p></div><button class="btn" data-route="store">${icon('plus')} Add games</button></div><div class="game-grid">${games.map(card).join('')||empty('Nothing here yet','Install a game from the real Store.',`<button class="btn primary" data-route="store">${icon('store')} Open Store</button>`)}</div>`;bindRoutes();bindCards();}
function renderSocial(){const el=$('#socialView');if(!el)return;el.innerHTML=`<div class="page-head"><div><span class="eyebrow">SOCIAL</span><h1>Social</h1><p>Confer, inside Flash Games.</p></div></div><section class="social-frame glass"><iframe src="https://itsmeh1.github.io/confer/confer.html?.amplify.com" title="Confer social" loading="lazy" allow="camera; microphone; display-capture; fullscreen; autoplay" referrerpolicy="no-referrer"></iframe></section>`;icons();}
function logIcon(type){const map={add:['plus','log-add'],edit:['hammer','log-edit'],remove:['x','log-remove']};const x=map[type]||map.edit;return `<span class="change-icon ${x[1]}">${icon(x[0])}</span>`}
async function renderUpdates(){const el=$('#updatesView');if(!el)return;const u=await FlashData.loadUpdates();const history=state.legacyHistory.length?state.legacyHistory.slice(0,100):[];el.innerHTML=`<div class="page-head"><div><span class="eyebrow">CHANGELOG</span><h1>What's new</h1><p>Real release data and migrated repository history.</p></div></div><div class="timeline">${u.releases.map(r=>`<article class="release glass"><div class="release-head"><div><strong>v${esc(r.version)}</strong><span>${esc(r.date)}</span></div><i data-lucide="sparkles"></i></div><p>${esc(r.desc||'')}</p>${(r.items||[]).map(item=>`<div class="log-item">${logIcon(item[0])}<span>${esc(item[1])}</span></div>`).join('')}</article>`).join('')}${history.length?`<article class="release glass"><div class="release-head"><div><strong>Legacy history</strong><span>${history.length} repository updates</span></div><i data-lucide="history"></i></div>${history.map(h=>`<div class="log-item legacy-log">${icon('git-commit-horizontal')}<span><b>${esc(h.title)}</b><small>${h.date.toLocaleDateString()}</small></span></div>`).join('')}</article>`:''}</div>`;icons();}
function profileName(){return state.profile?.username||state.profile?.displayName||state.profile?.name||state.user?.displayName||state.user?.email?.split('@')[0]||'Sign in'}
function profilePhoto(){return state.profile?.profilePicture||state.profile?.profilePic||state.profile?.avatar||state.profile?.photoURL||state.user?.photoURL||'./offline/logo.png'}
function updateProfileUI(){const name=profileName(),photo=profilePhoto();$('#headerName').textContent=name;$('#headerAvatar').innerHTML=`<span></span><img src="${esc(photo)}" alt="">`;$('#profileName').textContent=name;$('#profileEmail').textContent=state.user?.email||'Sign in to load your Firebase profile.';$('#profileAvatar').innerHTML=`<span></span><img src="${esc(photo)}" alt="">`;$('#profileGames').textContent=state.installed.size;$('#profileTotal').textContent=state.games.length;$('#signInBtn').hidden=!!state.user;$('#signOutBtn').hidden=!state.user;$('#authStatus').textContent=state.user?'Signed in with Firebase.':'Sign in to use your real account profile.';icons();}
async function openProfile(){updateProfileUI();$('#profilePanel').hidden=false;$('#settingsPanel').hidden=true;icons();}
async function authChanged(user){state.user=user;if(!user){state.profile=null;state.role='';$('#adminNav').classList.add('hidden');updateProfileUI();return;}try{const snap=await state.db.collection('users').doc(user.uid).get();state.profile=snap.exists?snap.data():null;state.role=String(state.profile?.role||'').toLowerCase();}catch{state.profile=null;state.role='';}$('#adminNav').classList.toggle('hidden',!ROLES.has(state.role));updateProfileUI();if(state.profile?.banned||state.profile?.status==='banned')toast('Account restricted','Your Firebase profile is marked as banned.');}
function renderAdmin(){const el=$('#adminView');if(!el)return;if(!ROLES.has(state.role)){el.innerHTML=empty('Admin unavailable','This area is only available to authorized Firebase roles.');return;}el.innerHTML=`<div class="page-head"><div><span class="eyebrow">MODERATION</span><h1>Admin</h1><p>Firebase-backed account management inside Flash Games.</p></div><button class="btn" id="adminRefresh">${icon('refresh')} Refresh</button></div><div class="admin-stats glass"><div><strong id="adminCount">—</strong><span>accounts</span></div><div><strong id="adminRestricted">—</strong><span>restricted</span></div><div><strong id="adminStaff">—</strong><span>staff</span></div></div><div class="admin-toolbar glass"><label class="search-bar">${icon('search')}<input id="adminSearch" placeholder="Search username or UID…"></label><select id="adminFilter"><option value="all">All</option><option value="active">Active</option><option value="restricted">Restricted</option><option value="staff">Staff</option></select></div><div class="user-table glass"><div class="user-head"><span>User</span><span>Role</span><span>Status</span><span>Updated</span><span></span></div><div id="adminRows">${empty('Loading','Reading Firebase users…')}</div></div>`;$('#adminRefresh').onclick=loadAdminUsers;$('#adminSearch').oninput=renderAdminRows;$('#adminFilter').onchange=renderAdminRows;loadAdminUsers();icons();}
let adminUsers=[];
function restricted(u){return u.deleted||u.status==='deleted'?'deleted':u.banned||u.status==='banned'?'banned':u.suspended||u.status==='suspended'?'suspended':''}
async function loadAdminUsers(){if(!state.db||!ROLES.has(state.role))return;try{const snap=await state.db.collection('users').limit(300).get();adminUsers=snap.docs.map(d=>({id:d.id,...d.data()}));$('#adminCount').textContent=adminUsers.length;$('#adminRestricted').textContent=adminUsers.filter(restricted).length;$('#adminStaff').textContent=adminUsers.filter(u=>ROLES.has(String(u.role||'').toLowerCase())).length;renderAdminRows();}catch(e){$('#adminRows').innerHTML=empty('Could not load users',e.message)}}
function renderAdminRows(){const q=($('#adminSearch')?.value||'').toLowerCase(),filter=$('#adminFilter')?.value||'all';const rows=adminUsers.filter(u=>{const r=restricted(u),staff=ROLES.has(String(u.role||'').toLowerCase()),name=String(u.username||u.displayName||u.name||u.email||'').toLowerCase();return(!q||(name+' '+u.id).includes(q))&&(filter==='all'||filter==='active'&&!r||filter==='restricted'&&r||filter==='staff'&&staff)});$('#adminRows').innerHTML=rows.length?rows.map(u=>{const r=restricted(u),name=u.username||u.displayName||u.name||u.email||u.id;return `<div class="user-line"><div class="person"><span class="avatar mini"><img src="${esc(u.profilePicture||u.profilePic||u.avatar||'./offline/logo.png')}" alt=""></span><span><b>${esc(name)}</b><small>${esc(u.id)}</small></span></div><span>${esc(u.role||'member')}</span><span class="status-label ${r?'bad':'good'}">${r||'active'}</span><span>${esc(u.updatedAt?.toDate?u.updatedAt.toDate().toLocaleDateString():u.updatedAt||'—')}</span><button class="icon-btn" data-manage-user="${esc(u.id)}" aria-label="Manage user">${icon('settings')}</button></div>`}).join(''):empty('No users','No Firebase users match this filter.');$$('[data-manage-user]').forEach(b=>b.onclick=()=>manageUser(b.dataset.manageUser));icons();}
async function manageUser(id){const u=adminUsers.find(x=>x.id===id);if(!u)return;const action=prompt(`Enter action for ${profileNameOf(u)}: ban, suspend, restore, delete`,'suspend')?.trim().toLowerCase();if(!['ban','suspend','restore','delete'].includes(action))return;const reason=prompt('Reason:')?.trim();if(!reason)return;const patch={updatedAt:firebase.firestore.Timestamp.now(),moderatedBy:state.user.uid,moderatorRole:state.role,moderationReason:reason};if(action==='ban')Object.assign(patch,{banned:true,status:'banned',banReason:reason,banAt:firebase.firestore.Timestamp.now()});if(action==='suspend')Object.assign(patch,{suspended:true,status:'suspended',suspensionReason:reason,suspensionAt:firebase.firestore.Timestamp.now()});if(action==='delete')Object.assign(patch,{deleted:true,status:'deleted',deletionReason:reason,deletedAt:firebase.firestore.Timestamp.now()});if(action==='restore')Object.assign(patch,{banned:false,suspended:false,deleted:false,status:'active',banReason:null,suspensionReason:null});try{await state.db.collection('users').doc(id).set(patch,{merge:true});toast('Moderation saved',`${profileNameOf(u)} was ${action==='restore'?'restored':action+'ned'}.`);loadAdminUsers();}catch(e){toast('Moderation failed',e.message)}}
function profileNameOf(u){return u.username||u.displayName||u.name||u.email||u.id}
function openSearch(){state.searchIndex=0;$('#searchBackdrop').hidden=false;$('#searchInput').value=state.query;updateSearch();setTimeout(()=>$('#searchInput').focus(),20)}
function updateSearch(){const q=$('#searchInput').value.toLowerCase().trim(),results=state.games.filter(g=>!q||`${g.name} ${g.category} ${g.description} ${(g.tags||[]).join(' ')}`.toLowerCase().includes(q)).slice(0,16);state.searchIndex=Math.min(state.searchIndex,Math.max(0,results.length-1));$('#searchResults').innerHTML=results.length?results.map((g,i)=>`<button class="search-result ${i===state.searchIndex?'selected':''}" data-search-play="${esc(g.id)}"><span class="result-cover">${g.cover?`<img src="${esc(g.cover)}" alt="">`:icon('gamepad-2')}</span><span class="result-copy"><strong>${esc(g.name)}</strong><span>${esc(g.category)} · ${esc(g.zone)}</span></span>${icon('arrow-up-right')}</button>`).join(''):empty('No games found','Try another search.');$$('[data-search-play]').forEach(b=>b.onclick=()=>{const g=state.games.find(x=>x.id===b.dataset.searchPlay);$('#searchBackdrop').hidden=true;if(g)launch(g)});icons();}
function launch(g){if(!g.url)return;$('#gameFrame').src=new URL(g.url,location.href).href;$('#playerOverlay').hidden=false;document.body.style.overflow='hidden';toast('Launching',g.name)}
function closePlayer(){$('#gameFrame').src='about:blank';$('#playerOverlay').hidden=true;document.body.style.overflow='';}
function renderNotifications(){const list=$('#notificationList');const rows=state.notifications.map(n=>`<article class="notification"><span class="notice-icon">${icon(n.type==='warning'?'triangle-alert':'bell')}</span><div><strong>${esc(n.title||n.message||'Notification')}</strong><p>${esc(n.body||n.message||'')}</p></div></article>`);if(!rows.length)rows.push(`<article class="notification"><span class="notice-icon">${icon('history')}</span><div><strong>No new notifications</strong><p>There are no Firebase notifications available for this account.</p></div></article>`);list.innerHTML=rows.join('');$('#notificationBadge').style.display=state.notifications.length?'block':'none';icons();}
async function openNotifications(){state.notifications=await FlashData.loadNotifications(state.user?.uid);renderNotifications();$('#notificationsBackdrop').hidden=false;}
function syncSettings(){const theme=localStorage.getItem('flashgames.theme')||'dark';$$('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===theme));$('#accentPicker').value=localStorage.getItem('flashgames.accent')||'#8b5cf6';$('#opacityRange').value=localStorage.getItem('flashgames.opacity')||66;$('#opacityValue').value=$('#opacityRange').value+'%';$('#blurRange').value=localStorage.getItem('flashgames.blur')||20;$('#blurValue').value=$('#blurRange').value+'px';$('.switch')?.classList.toggle('on',state.motion);}
function openSettings(){$('#profilePanel').hidden=true;$('#settingsPanel').hidden=false;syncSettings();icons();}
async function checkUpdate(){const u=await FlashData.loadUpdates(),previous=localStorage.getItem('flashgames.lastVersion');if(previous&&u.version&&previous!==u.version&&!sessionStorage.getItem('flashgames.reloaded')){sessionStorage.setItem('flashgames.reloaded','1');try{FlashData.clearCache();for(const key of await caches.keys())if(key.startsWith('flashgames-'))await caches.delete(key);if(navigator.serviceWorker){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()));}}catch{}localStorage.setItem('flashgames.lastVersion',u.version);location.replace(`${location.pathname}?updated=${encodeURIComponent(u.version)}#updates`);return false;}localStorage.setItem('flashgames.lastVersion',u.version);if(sessionStorage.getItem('flashgames.reloaded')){sessionStorage.removeItem('flashgames.reloaded');toast(`Updated to v${u.version}`,'New files loaded. Release notes are ready.');}return true;}
async function loadData(force=false){if(force)FlashData.clearCache();const r=await FlashData.loadGames(force);state.games=r.games||[];renderAll();toast(r.source==='legacy+offline'?'Catalogue restored':`Catalogue loaded`,`${state.games.length.toLocaleString()} real games`);}
function bindRoutes(){$$('[data-route]').forEach(b=>b.onclick=e=>{e.preventDefault();setRoute(b.dataset.route)});}
function init(){
 prefs();bindRoutes();
 $('#openSearch').onclick=openSearch;$('#openNotifications').onclick=openNotifications;$('#openProfile').onclick=openProfile;$('#openSettings').onclick=openSettings;$('#closePlayer').onclick=closePlayer;
 $$('[data-close]').forEach(b=>b.onclick=()=>{$('#'+b.dataset.close).hidden=true});
 $('#searchInput').oninput=e=>{state.query=e.target.value;state.searchIndex=0;updateSearch()};$('#searchBackdrop').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.hidden=true};$('#notificationsBackdrop').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.hidden=true};
 $('#themeChoices').onclick=e=>{const b=e.target.closest('[data-theme]');if(b){localStorage.setItem('flashgames.theme',b.dataset.theme);prefs();syncSettings()}};$('#accentPicker').oninput=e=>{localStorage.setItem('flashgames.accent',e.target.value);prefs()};$('#opacityRange').oninput=e=>{localStorage.setItem('flashgames.opacity',e.target.value);$('#opacityValue').value=e.target.value+'%';prefs()};$('#blurRange').oninput=e=>{localStorage.setItem('flashgames.blur',e.target.value);$('#blurValue').value=e.target.value+'px';prefs()};$('#toggleMotion').onclick=()=>{state.motion=!state.motion;localStorage.setItem('flashgames.motion',state.motion?'1':'0');prefs();syncSettings()};$('#clearLibrary').onclick=()=>{state.installed.clear();save();updateProfileUI();renderAll();toast('Library cleared')};
 $('#signInBtn').onclick=async()=>{try{await state.auth.signInWithEmailAndPassword($('#authEmail').value.trim(),$('#authPassword').value);toast('Signed in','Firebase profile loaded.')}catch(e){toast('Sign in failed',e.message)}};$('#signOutBtn').onclick=()=>state.auth.signOut();
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape'){['searchBackdrop','notificationsBackdrop','settingsPanel','profilePanel'].forEach(id=>{const x=$('#'+id);if(x)x.hidden=true});if(!$('#playerOverlay').hidden)closePlayer()}if(!$('#searchBackdrop').hidden&&e.key==='ArrowDown'){e.preventDefault();state.searchIndex=Math.min(state.searchIndex+1,$$('#searchResults .search-result').length-1);updateSearch()}if(!$('#searchBackdrop').hidden&&e.key==='ArrowUp'){e.preventDefault();state.searchIndex=Math.max(0,state.searchIndex-1);updateSearch()}if(!$('#searchBackdrop').hidden&&e.key==='Enter')$$('#searchResults .search-result')[state.searchIndex]?.click()});
 window.addEventListener('resize',()=>{const a=$('.desktop-nav .nav-item.active'),i=$('.nav-indicator');if(a&&i){i.style.width=a.offsetWidth+'px';i.style.transform=`translateX(${a.offsetLeft}px)`}});window.addEventListener('hashchange',()=>setRoute(location.hash.slice(1)||'home'));
 if(window.firebase){if(!firebase.apps.length)firebase.initializeApp(cfg);state.auth=firebase.auth();state.db=firebase.firestore();try{state.db.enablePersistence({synchronizeTabs:true}).catch(()=>{})}catch{}window.__flashFirebase={firebase,app:firebase.app(),auth:state.auth,db:state.db};state.auth.onAuthStateChanged(authChanged)}
 renderAll();
 FlashData.loadLegacyHistory().then(h=>{state.legacyHistory=h;renderUpdates()});
 checkUpdate().then(ok=>{if(ok)loadData(false)});
 if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
