(() => {
  'use strict';
  const GAME_CACHE='flashgames.catalogue.v4';
  const clean=value=>String(value??'').trim();
  const esc=value=>clean(value).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const normalizeGame=(g,index)=>{if(!g||typeof g!=='object')return null;const name=clean(g.name||g.title),url=clean(g.url||g.href||g.link);if(!name||!url)return null;return{id:clean(g.id)||`${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${index}`,name,title:name,url,zone:clean(g.zone||g.type||(g.isOfflinePackage?'OFFLINE':'STORE')),category:clean(g.category||g.genre||'Games'),description:clean(g.description||g.desc),cover:clean(g.cover||g.image||g.thumbnail||g.icon),tags:Array.isArray(g.tags)?g.tags.map(clean).filter(Boolean):[],rating:g.rating==null?null:Number(g.rating)}};
  const normalize=list=>Array.isArray(list)?list.map(normalizeGame).filter(Boolean):[];
  const cacheRead=()=>{try{const x=JSON.parse(localStorage.getItem(GAME_CACHE)||'null');return Array.isArray(x?.games)?x.games:[]}catch{return[]}};
  const cacheWrite=games=>{try{localStorage.setItem(GAME_CACHE,JSON.stringify({version:4,time:Date.now(),games}))}catch{}};
  const fetchJson=async(url,timeout=9000)=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(url,{cache:'no-store',signal:controller.signal,headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);return await response.json()}finally{clearTimeout(timer)}};
  function findAssignedArray(source){const markers=['STORE_GAMES','window.STORE_GAMES'];for(const marker of markers){let from=0;while((from=source.indexOf(marker,from))!==-1){const open=source.indexOf('[',from);if(open===-1){from+=marker.length;continue}let depth=0,quote='',escape=false;for(let i=open;i<source.length;i++){const ch=source[i];if(quote){if(escape)escape=false;else if(ch==='\\')escape=true;else if(ch===quote)quote='';continue}if(ch==='"'||ch==="'"){quote=ch;continue}if(ch==='[')depth++;else if(ch===']'){depth--;if(depth===0){const text=source.slice(open,i+1);try{const value=Function(`"use strict";return (${text})`)();if(Array.isArray(value))return value}catch{}break}}}from=open+1}}return[]}
  async function legacyStore(){try{const response=await fetch(`./legacy.html?v=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`legacy.html HTTP ${response.status}`);return normalize(findAssignedArray(await response.text()))}catch{return[]}}
  async function offlineCatalogue(){try{const payload=await fetchJson(`./offline.json?v=${Date.now()}`);return normalize(Array.isArray(payload)?payload:(payload.games||payload.data||[]))}catch{return[]}}
  async function configuredSource(){const base=clean(localStorage.getItem('flashgames.apiBase')||window.FLASH_API_BASE).replace(/\/$/,'');if(!base)return[];for(const endpoint of [`${base}/games`,`${base}/api/games`,`${base}/info`]){try{const payload=await fetchJson(endpoint);const list=normalize(payload?.games||payload?.data||payload);if(list.length)return list}catch{}}return[]}
  async function loadGames(force=false){if(!force){const cached=cacheRead();if(cached.length)return{games:cached,source:'cache'}}const remote=await configuredSource();if(remote.length){cacheWrite(remote);return{games:remote,source:'configured'}}const legacy=await legacyStore(),offline=await offlineCatalogue(),merged=[...legacy,...offline.filter(o=>!legacy.some(l=>l.url===o.url))];if(merged.length){cacheWrite(merged);return{games:merged,source:'legacy+offline'}}return{games:cacheRead(),source:'cache-stale'}}
  async function loadUpdates(){try{const payload=await fetchJson(`./update.json?v=${Date.now()}`),releases=Array.isArray(payload)?payload:(payload.releases||[]);return{version:clean(payload.version||releases[0]?.version||'0.0.0'),releases}}catch{return{version:'0.0.0',releases:[]}}}
  async function loadLegacyHistory(){try{const response=await fetch('https://api.github.com/repos/ItsMeh1/flashgames/commits?per_page=100',{cache:'no-store',headers:{Accept:'application/vnd.github+json'}});if(!response.ok)return[];const commits=await response.json();return Array.isArray(commits)?commits.map(c=>({version:'legacy',date:new Date(c.commit?.author?.date||c.commit?.committer?.date||Date.now()),title:clean(c.commit?.message||'Legacy update').split('\n')[0],sha:c.sha})).filter(x=>x.title):[]}catch{return[]}}
  async function loadNotifications(uid){const db=window.__flashFirebase?.db;if(!db)return[];try{const base=db.collection('notifications');let snap;if(uid){try{snap=await base.where('uid','==',uid).orderBy('createdAt','desc').limit(30).get()}catch{snap=await base.orderBy('createdAt','desc').limit(30).get()}}else snap=await base.orderBy('createdAt','desc').limit(30).get();return snap.docs.map(d=>({id:d.id,...d.data()}))}catch{return[]}}
  async function getPresenceCount(){const db=window.__flashFirebase?.db;if(!db)return null;for(const collection of ['presence','onlineUsers']){try{const snap=await db.collection(collection).get();if(snap.size)return snap.size}catch{}}return null}
  window.FlashData={loadGames,loadUpdates,loadLegacyHistory,loadNotifications,getPresenceCount,clearCache:()=>localStorage.removeItem(GAME_CACHE),esc};
})();
