(() => {
'use strict';
const GAME_CACHE='flashgames.catalogue.v6';
const clean=v=>String(v??'').trim();
const esc=v=>clean(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const stableId=(g,i)=>clean(g.id)||clean(g.url)||`${clean(g.name).toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${i}`;
const normalizeGame=(g,i)=>{if(!g||typeof g!=='object')return null;const name=clean(g.name||g.title),url=clean(g.url||g.href||g.link);if(!name||!url)return null;return{id:stableId(g,i),name,title:name,url,zone:clean(g.zone||g.type||(g.isOfflinePackage?'OFFLINE':'STORE')),category:clean(g.category||g.genre||'Games'),description:clean(g.description||g.desc),cover:clean(g.cover||g.image||g.thumbnail||g.icon),tags:Array.isArray(g.tags)?g.tags.map(clean).filter(Boolean):[],rating:g.rating==null?null:Number(g.rating)}};
const normalize=list=>Array.isArray(list)?list.map(normalizeGame).filter(Boolean):[];
const dedupe=list=>{const seen=new Set();return list.filter(g=>{const key=clean(g.url)||g.id;if(seen.has(key))return false;seen.add(key);return true})};
const cacheRead=()=>{try{const x=JSON.parse(localStorage.getItem(GAME_CACHE)||'null');return Array.isArray(x?.games)?x.games:[]}catch{return[]}};
const legacyCacheRead=()=>{for(const key of ['flashgames.catalogue.v5','flashgames.catalogue.v4','flashgames.catalogue.v3']){try{const x=JSON.parse(localStorage.getItem(key)||'null');if(Array.isArray(x?.games))return x.games}catch{}}return[]};
const cacheWrite=games=>{try{localStorage.setItem(GAME_CACHE,JSON.stringify({version:6,time:Date.now(),games}))}catch{}};
const fetchJson=async(url,timeout=12000)=>{const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal,headers:{Accept:'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}};
function findAssignedArray(source){for(const marker of ['STORE_GAMES','window.STORE_GAMES']){let from=0;while((from=source.indexOf(marker,from))!==-1){const open=source.indexOf('[',from);if(open<0){from+=marker.length;continue}let depth=0,quote='',escaped=false;for(let i=open;i<source.length;i++){const ch=source[i];if(quote){if(escaped)escaped=false;else if(ch==='\\')escaped=true;else if(ch===quote)quote='';continue}if(ch==='\"'||ch==="'"){quote=ch;continue}if(ch==='[')depth++;if(ch===']'){depth--;if(!depth){try{const value=Function(`\"use strict\";return (${source.slice(open,i+1)})`)();if(Array.isArray(value))return value}catch{}break}}}from=open+1}}return[]}
async function legacyStore(){const urls=['./legacy.html','https://raw.githubusercontent.com/ItsMeh1/flashgames/main/index.html','https://raw.githubusercontent.com/ItsMeh1/flashgames/v2/legacy.html'];for(const u of urls){try{const r=await fetch(`${u}${u.includes('?')?'&':'?'}v=${Date.now()}`,{cache:'no-store'});if(!r.ok)continue;const games=normalize(findAssignedArray(await r.text()));if(games.length)return games}catch{}}return[]}
async function offlineCatalogue(){try{const p=await fetchJson(`./offline.json?v=${Date.now()}`);return normalize(Array.isArray(p)?p:(p.games||p.data||[]))}catch{return[]}}
async function configuredSource(){const base=clean(localStorage.getItem('flashgames.apiBase')||window.FLASH_API_BASE).replace(/\/$/,'');if(!base)return[];for(const endpoint of [`${base}/games`,`${base}/api/games`,`${base}/info`]){try{const p=await fetchJson(endpoint);const list=normalize(p?.games||p?.data||p);if(list.length)return list}catch{}}return[]}
async function loadGames(force=false){const old=dedupe(normalize([...cacheRead(),...legacyCacheRead()]));if(!force&&old.length){cacheWrite(old);return{games:old,source:'cache'}}const remote=await configuredSource();if(remote.length){const merged=dedupe([...remote,...old]);cacheWrite(merged);return{games:merged,source:'configured+cache'}}const legacy=await legacyStore(),offline=await offlineCatalogue(),merged=dedupe([...legacy,...offline,...old]);if(merged.length){cacheWrite(merged);return{games:merged,source:'legacy+offline+cache'}}return{games:old,source:'cache-stale'}}
async function loadUpdates(){try{const p=await fetchJson(`./update.json?v=${Date.now()}`),r=Array.isArray(p)?p:(p.releases||[]);return{version:clean(p.version||r[0]?.version||'0.0.0'),releases:r}}catch{return{version:'0.0.0',releases:[]}}}
async function loadLegacyHistory(){try{const r=await fetch('https://api.github.com/repos/ItsMeh1/flashgames/commits?per_page=100',{cache:'no-store',headers:{Accept:'application/vnd.github+json'}});if(!r.ok)return[];const c=await r.json();return Array.isArray(c)?c.map(x=>({date:new Date(x.commit?.author?.date||x.commit?.committer?.date||Date.now()),title:clean(x.commit?.message||'Legacy update').split('\n')[0],sha:x.sha})):[]}catch{return[]}}
async function loadNotifications(uid){const db=window.__flashFirebase?.db;if(!db)return[];try{const base=db.collection('notifications');let s;try{s=uid?await base.where('uid','==',uid).limit(30).get():await base.limit(30).get()}catch{s=await base.limit(30).get()}return s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>Number(b.createdAt?.seconds||b.createdAt||0)-Number(a.createdAt?.seconds||a.createdAt||0))}catch{return[]}}
async function getPresenceCount(){const db=window.__flashFirebase?.db;if(!db)return null;for(const c of ['presence','onlineUsers']){try{const s=await db.collection(c).get();if(s.size)return s.size}catch{}}return null}
window.FlashData={loadGames,loadUpdates,loadLegacyHistory,loadNotifications,getPresenceCount,clearCache:()=>localStorage.removeItem(GAME_CACHE),esc};
})();
